### ISSUE TITLE
"Do you want to leave the page? All your unsaved changes will be lost."

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/RecordWizard#14] opened 2022-01-28 10:48 UTC
[MediaWiki:Common.js](https://lingualibre.org/wiki/MediaWiki:Common.js) add a modal warning on leaving : 

```javascript
/* *************************************************************** */
/* RECORD WIZARD SUGAR ******************************************* */
/*Confirmation message when users try to leave the Record Wizard
(works from the second step onwards) */
$(function() {
if (mw.config.get('wgPageName') !== 'Special:RecordWizard') {
    return;
}
window.onbeforeunload = function() {
    return "Do you want to leave the page? All your unsaved changes will be lost.";
};
});
/*
if (mw.config.get('wgPageName') === 'Special:RecordWizard') {
    window.onbeforeunload = function() {
        return "Do you want to leave the page? All your unsaved changes will be lost.";
    };
}
*/
```

This could be integrated to the plugin itself.

**Comment by Poslovitch** [comment] 2022-01-28 21:57
Duplicate of https://phabricator.wikimedia.org/T274864

**Closed as completed by Poslovitch** 2022-01-28 21:57 UTC
